In [5]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

# 创建更多数据
datas = np.array([
    [1.0, 2.0, 3.0],
    [4.0, 5.0, 6.0],
    [7.0, 8.0, 9.0],
    [10.0, 11.0, 12.0],
    [13.0, 14.0, 15.0],
    [16.0, 17.0, 18.0],
    [-19.0, -20.0, 21.0],
    [221.0, 231.0, 214.0]
])

# 创建MinMaxScaler对象
scaler = MinMaxScaler(feature_range=(0, 1))

# 拟合并转换数据
scaled_data = scaler.fit_transform(datas)

print("原始数据：\n", datas)
print("\n归一化后的数据：\n", scaled_data)
# 创建MinMaxScaler对象，设置归一化范围为[-1, 1]
scaler = MinMaxScaler(feature_range=(-1, 1))#用feature_range参数设置归一化范围

# 拟合并转换数据
scaled_data = scaler.fit_transform(datas)

print("\n归一化到[-1,1]后的数据：\n", scaled_data)






原始数据：
 [[  1.   2.   3.]
 [  4.   5.   6.]
 [  7.   8.   9.]
 [ 10.  11.  12.]
 [ 13.  14.  15.]
 [ 16.  17.  18.]
 [-19. -20.  21.]
 [221. 231. 214.]]

归一化后的数据：
 [[0.08333333 0.0876494  0.        ]
 [0.09583333 0.09960159 0.01421801]
 [0.10833333 0.11155378 0.02843602]
 [0.12083333 0.12350598 0.04265403]
 [0.13333333 0.13545817 0.05687204]
 [0.14583333 0.14741036 0.07109005]
 [0.         0.         0.08530806]
 [1.         1.         1.        ]]

归一化到[-1,1]后的数据：
 [[-0.83333333 -0.8247012  -1.        ]
 [-0.80833333 -0.80079681 -0.97156398]
 [-0.78333333 -0.77689243 -0.94312796]
 [-0.75833333 -0.75298805 -0.91469194]
 [-0.73333333 -0.72908367 -0.88625592]
 [-0.70833333 -0.70517928 -0.85781991]
 [-1.         -1.         -0.82938389]
 [ 1.          1.          1.        ]]


In [6]:
from sklearn.preprocessing import StandardScaler

# 创建包含异常点的数据
data_with_outliers = np.array([
    [1.0, 2.0, 3.0],
    [4.0, 5.0, 6.0],
    [7.0, 8.0, 9.0],
    [10.0, 11.0, 12.0],
    [100.0, 200.0, 300.0],  # 异常点
    [-50.0, -100.0, -150.0],  # 异常点
    [22.0, 23.0, 24.0],
    [25.0, 26.0, 27.0]
])

# 创建StandardScaler对象
scaler = StandardScaler()

# 拟合并转换数据
scaled_data = scaler.fit_transform(data_with_outliers)

print("包含异常点的原始数据：\n", data_with_outliers)
print("\n标准化后的数据：\n", scaled_data)



包含异常点的原始数据：
 [[   1.    2.    3.]
 [   4.    5.    6.]
 [   7.    8.    9.]
 [  10.   11.   12.]
 [ 100.  200.  300.]
 [ -50. -100. -150.]
 [  22.   23.   24.]
 [  25.   26.   27.]]

标准化后的数据：
 [[-0.35817821 -0.25768568 -0.22331267]
 [-0.28073427 -0.21878973 -0.19742134]
 [-0.20329034 -0.17989378 -0.17153002]
 [-0.1258464  -0.14099783 -0.14563869]
 [ 2.19747173  2.30944714  2.33992836]
 [-1.67472515 -1.58014804 -1.54377016]
 [ 0.18392935  0.01458598 -0.0420734 ]
 [ 0.26137329  0.05348193 -0.01618208]]


In [7]:
from sklearn.impute import SimpleImputer
import numpy as np

# 创建包含缺失值的数据
data_with_missing = np.array([
    [1.0, 2.0, np.nan],
    [4.0, np.nan, 6.0],
    [7.0, 8.0, 9.0],
    [np.nan, 11.0, 12.0],
    [13.0, 14.0, 15.0]
])

# 创建SimpleImputer对象，使用均值填充缺失值
imputer = SimpleImputer(strategy='mean')#strategy参数用于指定填充策略，mean表示使用均值填充，median表示使用中位数填充，most_frequent表示使用最频繁的值填充
#根据具体场景选择填充策略，例如：
# 如果数据中存在大量缺失值，可以使用均值填充，但可能会引入偏差
# 如果数据中存在少量缺失值，可以使用中位数填充，但可能会引入偏差
# 如果数据中存在大量重复值，可以使用最频繁的值填充，但可能会引入偏差
# 如果数据中存在大量异常值，可以使用中位数填充，但可能会引入偏差

# 拟合并转换数据
imputed_data = imputer.fit_transform(data_with_missing)

print("包含缺失值的原始数据：\n", data_with_missing)
print("\n缺失值插补后的数据：\n", imputed_data)


包含缺失值的原始数据：
 [[ 1.  2. nan]
 [ 4. nan  6.]
 [ 7.  8.  9.]
 [nan 11. 12.]
 [13. 14. 15.]]

缺失值插补后的数据：
 [[ 1.    2.   10.5 ]
 [ 4.    8.75  6.  ]
 [ 7.    8.    9.  ]
 [ 6.25 11.   12.  ]
 [13.   14.   15.  ]]
