In [1]:
from sklearn.feature_selection import VarianceThreshold#VarianceThreshold是用于特征选择的类，用于删除方差小于阈值的特征/
import numpy as np

# 创建示例数据
X = np.array([[0, 2, 0, 3], 
              [0, 1, 4, 3], 
              [0, 1, 1, 3]])

# 创建VarianceThreshold对象，设置阈值为0.8
selector = VarianceThreshold(threshold=0.8)#threshold参数用于设置阈值，默认值为0，表示不进行特征选择

# 拟合并转换数据
X_new = selector.fit_transform(X)

print("原始数据：\n", X)
print("特征方差：", selector.variances_)
print("筛选后的数据：\n", X_new)


原始数据：
 [[0 2 0 3]
 [0 1 4 3]
 [0 1 1 3]]
特征方差： [0.         0.22222222 2.88888889 0.        ]
筛选后的数据：
 [[0]
 [4]
 [1]]


In [2]:
from sklearn.decomposition import PCA#PCA是用于主成分分析的类，用于将高维数据降维到低维空间

# 创建示例数据
X = np.array([[0, 2, 0, 3], 
              [0, 1, 4, 3], 
              [0, 1, 1, 3]])

# 创建PCA对象，设置主成分个数为2
pca = PCA(n_components=2)#n_components参数用于设置主成分个数，默认值为None，表示不进行主成分分析

# 拟合并转换数据
X_pca = pca.fit_transform(X)

print("原始数据：\n", X)
print("PCA降维后的数据：\n", X_pca)
print("各主成分的方差解释比例：", pca.explained_variance_ratio_)



原始数据：
 [[0 2 0 3]
 [0 1 4 3]
 [0 1 1 3]]
PCA降维后的数据：
 [[-1.76504522  0.32686023]
 [ 2.35339362  0.13074409]
 [-0.58834841 -0.45760432]]
各主成分的方差解释比例： [0.96428571 0.03571429]
